/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_pass_dialog (void)
{
  GtkWidget *pass_dialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox1;
  GtkWidget *label2;
  GtkWidget *hbox2;
  GtkWidget *user_name;
  GtkWidget *entry5;
  GtkWidget *pass_status;
  GtkWidget *hbox3;
  GtkWidget *label1;
  GtkWidget *entry1;
  GtkWidget *dialog_action_area1;
  GtkWidget *okbutton1;

  pass_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (pass_dialog), _("Login Screen"));
  gtk_window_set_position (GTK_WINDOW (pass_dialog), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (pass_dialog), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (pass_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (pass_dialog)->vbox;
  gtk_widget_show (dialog_vbox1);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox1, FALSE, FALSE, 0);
  gtk_widget_set_size_request (vbox1, 248, -1);

  label2 = gtk_label_new (_("Welcome to USB File Protector"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (vbox1), label2, FALSE, FALSE, 20);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_CENTER);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, TRUE, TRUE, 0);

  user_name = gtk_label_new (_("User Name:"));
  gtk_widget_show (user_name);
  gtk_box_pack_start (GTK_BOX (hbox2), user_name, FALSE, FALSE, 5);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_box_pack_start (GTK_BOX (hbox2), entry5, TRUE, TRUE, 5);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 9679);

  pass_status = gtk_label_new ("");
  gtk_widget_show (pass_status);
  gtk_box_pack_start (GTK_BOX (vbox1), pass_status, FALSE, FALSE, 5);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox3, TRUE, TRUE, 5);

  label1 = gtk_label_new (_("Password:"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox3), label1, FALSE, FALSE, 9);
  gtk_widget_set_size_request (label1, -1, 15);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (hbox3), entry1, TRUE, TRUE, 5);
  gtk_widget_set_size_request (entry1, 162, -1);
  gtk_entry_set_visibility (GTK_ENTRY (entry1), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 9679);

  dialog_action_area1 = GTK_DIALOG (pass_dialog)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_EDGE);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (pass_dialog), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) pass_dialog, "delete_event",
                    G_CALLBACK (gtk_true),
                    NULL);
  g_signal_connect_swapped ((gpointer) okbutton1, "clicked",
                            G_CALLBACK (on_okbutton1_clicked),
                            GTK_OBJECT (pass_dialog));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (pass_dialog, pass_dialog, "pass_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (pass_dialog, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (pass_dialog, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (pass_dialog, label2, "label2");
  GLADE_HOOKUP_OBJECT (pass_dialog, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (pass_dialog, user_name, "user_name");
  GLADE_HOOKUP_OBJECT (pass_dialog, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (pass_dialog, pass_status, "pass_status");
  GLADE_HOOKUP_OBJECT (pass_dialog, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (pass_dialog, label1, "label1");
  GLADE_HOOKUP_OBJECT (pass_dialog, entry1, "entry1");
  GLADE_HOOKUP_OBJECT_NO_REF (pass_dialog, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (pass_dialog, okbutton1, "okbutton1");

  return pass_dialog;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox3;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *add_file_to_device;
  GtkWidget *image9;
  GtkWidget *add_folder_to_device;
  GtkWidget *image10;
  GtkWidget *extract_to_local_machine;
  GtkWidget *image11;
  GtkWidget *delete_from_device;
  GtkWidget *image12;
  GtkWidget *separator1;
  GtkWidget *quit;
  GtkWidget *image13;
  GtkWidget *menuitem2;
  GtkWidget *menuitem2_menu;
  GtkWidget *apply_changes;
  GtkWidget *image14;
  GtkWidget *separator2;
  GtkWidget *change_password;
  GtkWidget *image15;
  GtkWidget *menuitem3;
  GtkWidget *menuitem3_menu;
  GtkWidget *device_properties;
  GtkWidget *image16;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *usage_instructions;
  GtkWidget *image17;
  GtkWidget *about;
  GtkWidget *image18;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *toolbutton1;
  GtkWidget *toolbutton2;
  GtkWidget *toolbutton3;
  GtkWidget *toolbutton4;
  GtkWidget *toolitem1;
  GtkWidget *vseparator1;
  GtkWidget *clear_toolButton;
  GtkWidget *toolbutton5;
  GtkWidget *toolitem2;
  GtkWidget *vseparator2;
  GtkWidget *toolbar_add_user;
  GtkWidget *toolbutton6;
  GtkWidget *toolbutton9;
  GtkWidget *toolitem3;
  GtkWidget *vseparator3;
  GtkWidget *toolbutton7;
  GtkWidget *hpaned1;
  GtkWidget *scrolledwindow1;
  GtkWidget *dir_view;
  GtkWidget *scrolledwindow2;
  GtkWidget *file_view;
  GtkWidget *progressbar;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("Main Window"));
  gtk_window_set_default_size (GTK_WINDOW (window1), 800, 600);
  gtk_window_set_gravity (GTK_WINDOW (window1), GDK_GRAVITY_STATIC);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (window1), vbox3);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox3), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  add_file_to_device = gtk_image_menu_item_new_with_mnemonic (_("Add File to DEVICE"));
  gtk_widget_show (add_file_to_device);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), add_file_to_device);

  image9 = gtk_image_new_from_stock ("gtk-copy", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image9);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (add_file_to_device), image9);

  add_folder_to_device = gtk_image_menu_item_new_with_mnemonic (_("Add Folder to DEVICE"));
  gtk_widget_show (add_folder_to_device);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), add_folder_to_device);

  image10 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image10);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (add_folder_to_device), image10);

  extract_to_local_machine = gtk_image_menu_item_new_with_mnemonic (_("Extract to Local Machine"));
  gtk_widget_show (extract_to_local_machine);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), extract_to_local_machine);

  image11 = gtk_image_new_from_stock ("gtk-convert", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image11);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (extract_to_local_machine), image11);

  delete_from_device = gtk_image_menu_item_new_with_mnemonic (_("Delete from DEVICE"));
  gtk_widget_show (delete_from_device);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), delete_from_device);

  image12 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image12);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (delete_from_device), image12);

  separator1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  quit = gtk_image_menu_item_new_with_mnemonic (_("Quit"));
  gtk_widget_show (quit);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quit);

  image13 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image13);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (quit), image13);

  menuitem2 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (menuitem2);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem2);

  menuitem2_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem2), menuitem2_menu);

  apply_changes = gtk_image_menu_item_new_with_mnemonic (_("Apply Changes"));
  gtk_widget_show (apply_changes);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), apply_changes);

  image14 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image14);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (apply_changes), image14);

  separator2 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  change_password = gtk_image_menu_item_new_with_mnemonic (_("Change Password"));
  gtk_widget_show (change_password);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), change_password);

  image15 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image15);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (change_password), image15);

  menuitem3 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (menuitem3);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem3);

  menuitem3_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem3), menuitem3_menu);

  device_properties = gtk_image_menu_item_new_with_mnemonic (_("DEVICE Properties"));
  gtk_widget_show (device_properties);
  gtk_container_add (GTK_CONTAINER (menuitem3_menu), device_properties);

  image16 = gtk_image_new_from_stock ("gtk-properties", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image16);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (device_properties), image16);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  usage_instructions = gtk_image_menu_item_new_with_mnemonic (_("Usage Instructions"));
  gtk_widget_show (usage_instructions);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), usage_instructions);

  image17 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image17);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (usage_instructions), image17);

  about = gtk_image_menu_item_new_with_mnemonic (_("About"));
  gtk_widget_show (about);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about);

  image18 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image18);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (about), image18);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox3), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  tmp_image = gtk_image_new_from_stock ("gtk-copy", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbutton1 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Add File"));
  gtk_widget_show (toolbutton1);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton1);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton1), tooltips, _("Add an individual File to the DEVICE"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-open", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbutton2 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Add Folder"));
  gtk_widget_show (toolbutton2);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton2);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton2), tooltips, _("Add a complete Folder to the DEVICE"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-convert", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbutton3 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Extract"));
  gtk_widget_show (toolbutton3);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton3);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton3), tooltips, _("Extract selected Files to Local Machine"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-delete", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbutton4 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Delete"));
  gtk_widget_show (toolbutton4);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton4);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton4), tooltips, _("Delete selected Files/Folders from DEVICE"), NULL);

  toolitem1 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolitem1);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_container_add (GTK_CONTAINER (toolitem1), vseparator1);

  tmp_image = gtk_image_new_from_stock ("gtk-undo", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  clear_toolButton = (GtkWidget*) gtk_tool_button_new (tmp_image, _("  Clear\nChanges"));
  gtk_widget_show (clear_toolButton);
  gtk_container_add (GTK_CONTAINER (toolbar1), clear_toolButton);

  tmp_image = gtk_image_new_from_stock ("gtk-apply", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbutton5 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("   Apply \nChanges"));
  gtk_widget_show (toolbutton5);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton5);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton5), tooltips, _("Apply Add/Extract/Delete Operations"), NULL);

  toolitem2 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem2);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolitem2);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_container_add (GTK_CONTAINER (toolitem2), vseparator2);

  tmp_image = gtk_image_new_from_stock ("gtk-add", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbar_add_user = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Add User"));
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbar_add_user);

  tmp_image = gtk_image_new_from_stock ("gtk-dialog-authentication", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbutton6 = (GtkWidget*) gtk_tool_button_new (tmp_image, _(" Change\nPassword"));
  gtk_widget_show (toolbutton6);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton6);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton6), tooltips, _("Change Master Password for DEVICE"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-properties", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbutton9 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("  DEVICE\nProperties"));
  gtk_widget_show (toolbutton9);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton9);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton9), tooltips, _("View DEVICE Properties"), NULL);

  toolitem3 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem3);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolitem3);

  vseparator3 = gtk_vseparator_new ();
  gtk_widget_show (vseparator3);
  gtk_container_add (GTK_CONTAINER (toolitem3), vseparator3);

  tmp_image = gtk_image_new_from_stock ("gtk-quit", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbutton7 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Quit"));
  gtk_widget_show (toolbutton7);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton7);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton7), tooltips, _("Bye-Bye"), NULL);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox3), hpaned1, TRUE, TRUE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_paned_pack1 (GTK_PANED (hpaned1), scrolledwindow1, FALSE, TRUE);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  dir_view = gtk_tree_view_new ();
  gtk_widget_show (dir_view);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), dir_view);
  gtk_widget_set_size_request (dir_view, 120, -1);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_paned_pack2 (GTK_PANED (hpaned1), scrolledwindow2, TRUE, TRUE);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  file_view = gtk_tree_view_new ();
  gtk_widget_show (file_view);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), file_view);

  progressbar = gtk_progress_bar_new ();
  gtk_widget_show (progressbar);
  gtk_box_pack_start (GTK_BOX (vbox3), progressbar, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) window1, "delete_event",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) add_file_to_device, "activate",
                    G_CALLBACK (on_add_file_to_device_activate),
                    NULL);
  g_signal_connect ((gpointer) add_folder_to_device, "activate",
                    G_CALLBACK (on_add_folder_to_device_activate),
                    NULL);
  g_signal_connect ((gpointer) extract_to_local_machine, "activate",
                    G_CALLBACK (on_extract_to_local_machine_activate),
                    NULL);
  g_signal_connect ((gpointer) delete_from_device, "activate",
                    G_CALLBACK (on_delete_from_device_activate),
                    NULL);
  g_signal_connect ((gpointer) quit, "activate",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) apply_changes, "activate",
                    G_CALLBACK (on_apply_changes_activate),
                    NULL);
  g_signal_connect ((gpointer) change_password, "activate",
                    G_CALLBACK (on_change_password_activate),
                    NULL);
  g_signal_connect ((gpointer) device_properties, "activate",
                    G_CALLBACK (on_device_properties_activate),
                    NULL);
  g_signal_connect ((gpointer) usage_instructions, "activate",
                    G_CALLBACK (on_usage_instructions_activate),
                    NULL);
  g_signal_connect ((gpointer) about, "activate",
                    G_CALLBACK (on_about_activate),
                    NULL);
  g_signal_connect ((gpointer) toolbutton1, "clicked",
                    G_CALLBACK (on_toolbutton1_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton2, "clicked",
                    G_CALLBACK (on_toolbutton2_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton3, "clicked",
                    G_CALLBACK (on_toolbutton3_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton4, "clicked",
                    G_CALLBACK (on_toolbutton4_clicked),
                    NULL);
  g_signal_connect ((gpointer) clear_toolButton, "clicked",
                    G_CALLBACK (on_clear_toolButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton5, "clicked",
                    G_CALLBACK (on_toolbutton5_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbar_add_user, "clicked",
                    G_CALLBACK (on_toolbar_add_user_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton6, "clicked",
                    G_CALLBACK (on_toolbutton6_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton7, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) dir_view, "cursor_changed",
                    G_CALLBACK (on_dir_view_cursor_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (window1, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (window1, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (window1, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (window1, add_file_to_device, "add_file_to_device");
  GLADE_HOOKUP_OBJECT (window1, image9, "image9");
  GLADE_HOOKUP_OBJECT (window1, add_folder_to_device, "add_folder_to_device");
  GLADE_HOOKUP_OBJECT (window1, image10, "image10");
  GLADE_HOOKUP_OBJECT (window1, extract_to_local_machine, "extract_to_local_machine");
  GLADE_HOOKUP_OBJECT (window1, image11, "image11");
  GLADE_HOOKUP_OBJECT (window1, delete_from_device, "delete_from_device");
  GLADE_HOOKUP_OBJECT (window1, image12, "image12");
  GLADE_HOOKUP_OBJECT (window1, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (window1, quit, "quit");
  GLADE_HOOKUP_OBJECT (window1, image13, "image13");
  GLADE_HOOKUP_OBJECT (window1, menuitem2, "menuitem2");
  GLADE_HOOKUP_OBJECT (window1, menuitem2_menu, "menuitem2_menu");
  GLADE_HOOKUP_OBJECT (window1, apply_changes, "apply_changes");
  GLADE_HOOKUP_OBJECT (window1, image14, "image14");
  GLADE_HOOKUP_OBJECT (window1, separator2, "separator2");
  GLADE_HOOKUP_OBJECT (window1, change_password, "change_password");
  GLADE_HOOKUP_OBJECT (window1, image15, "image15");
  GLADE_HOOKUP_OBJECT (window1, menuitem3, "menuitem3");
  GLADE_HOOKUP_OBJECT (window1, menuitem3_menu, "menuitem3_menu");
  GLADE_HOOKUP_OBJECT (window1, device_properties, "device_properties");
  GLADE_HOOKUP_OBJECT (window1, image16, "image16");
  GLADE_HOOKUP_OBJECT (window1, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (window1, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (window1, usage_instructions, "usage_instructions");
  GLADE_HOOKUP_OBJECT (window1, image17, "image17");
  GLADE_HOOKUP_OBJECT (window1, about, "about");
  GLADE_HOOKUP_OBJECT (window1, image18, "image18");
  GLADE_HOOKUP_OBJECT (window1, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (window1, toolbutton1, "toolbutton1");
  GLADE_HOOKUP_OBJECT (window1, toolbutton2, "toolbutton2");
  GLADE_HOOKUP_OBJECT (window1, toolbutton3, "toolbutton3");
  GLADE_HOOKUP_OBJECT (window1, toolbutton4, "toolbutton4");
  GLADE_HOOKUP_OBJECT (window1, toolitem1, "toolitem1");
  GLADE_HOOKUP_OBJECT (window1, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (window1, clear_toolButton, "clear_toolButton");
  GLADE_HOOKUP_OBJECT (window1, toolbutton5, "toolbutton5");
  GLADE_HOOKUP_OBJECT (window1, toolitem2, "toolitem2");
  GLADE_HOOKUP_OBJECT (window1, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (window1, toolbar_add_user, "toolbar_add_user");
  GLADE_HOOKUP_OBJECT (window1, toolbutton6, "toolbutton6");
  GLADE_HOOKUP_OBJECT (window1, toolbutton9, "toolbutton9");
  GLADE_HOOKUP_OBJECT (window1, toolitem3, "toolitem3");
  GLADE_HOOKUP_OBJECT (window1, vseparator3, "vseparator3");
  GLADE_HOOKUP_OBJECT (window1, toolbutton7, "toolbutton7");
  GLADE_HOOKUP_OBJECT (window1, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window1, dir_view, "dir_view");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (window1, file_view, "file_view");
  GLADE_HOOKUP_OBJECT (window1, progressbar, "progressbar");
  GLADE_HOOKUP_OBJECT_NO_REF (window1, tooltips, "tooltips");

  return window1;
}

GtkWidget*
create_filechooserdialog_file (void)
{
  GtkWidget *filechooserdialog_file;
  GtkWidget *dialog_vbox3;
  GtkWidget *dialog_action_area3;
  GtkWidget *button3;
  GtkWidget *button4;

  filechooserdialog_file = gtk_file_chooser_dialog_new ("", NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_container_set_border_width (GTK_CONTAINER (filechooserdialog_file), 5);
  gtk_window_set_type_hint (GTK_WINDOW (filechooserdialog_file), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox3 = GTK_DIALOG (filechooserdialog_file)->vbox;
  gtk_widget_show (dialog_vbox3);

  dialog_action_area3 = GTK_DIALOG (filechooserdialog_file)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  button3 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button3);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog_file), button3, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  button4 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (button4);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog_file), button4, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) button3, "clicked",
                            G_CALLBACK (on_button3_clicked),
                            GTK_OBJECT (filechooserdialog_file));
  g_signal_connect_swapped ((gpointer) button4, "clicked",
                            G_CALLBACK (on_button4_clicked),
                            GTK_OBJECT (filechooserdialog_file));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog_file, filechooserdialog_file, "filechooserdialog_file");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog_file, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog_file, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (filechooserdialog_file, button3, "button3");
  GLADE_HOOKUP_OBJECT (filechooserdialog_file, button4, "button4");

  gtk_widget_grab_default (button4);
  return filechooserdialog_file;
}

GtkWidget*
create_filechooserdialog_dir (void)
{
  GtkWidget *filechooserdialog_dir;
  GtkWidget *dialog_vbox4;
  GtkWidget *dialog_action_area4;
  GtkWidget *button5;
  GtkWidget *button6;

  filechooserdialog_dir = gtk_file_chooser_dialog_new ("", NULL, GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER, NULL);
  gtk_container_set_border_width (GTK_CONTAINER (filechooserdialog_dir), 5);
  gtk_window_set_type_hint (GTK_WINDOW (filechooserdialog_dir), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox4 = GTK_DIALOG (filechooserdialog_dir)->vbox;
  gtk_widget_show (dialog_vbox4);

  dialog_action_area4 = GTK_DIALOG (filechooserdialog_dir)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  button5 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button5);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog_dir), button5, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button5, GTK_CAN_DEFAULT);

  button6 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (button6);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog_dir), button6, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button6, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) button5, "clicked",
                            G_CALLBACK (on_button5_clicked),
                            GTK_OBJECT (filechooserdialog_dir));
  g_signal_connect_swapped ((gpointer) button6, "clicked",
                            G_CALLBACK (on_button6_clicked),
                            GTK_OBJECT (filechooserdialog_dir));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog_dir, filechooserdialog_dir, "filechooserdialog_dir");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog_dir, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog_dir, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (filechooserdialog_dir, button5, "button5");
  GLADE_HOOKUP_OBJECT (filechooserdialog_dir, button6, "button6");

  gtk_widget_grab_default (button6);
  return filechooserdialog_dir;
}

GtkWidget*
create_filechooserdialog_extract (void)
{
  GtkWidget *filechooserdialog_extract;
  GtkWidget *dialog_vbox5;
  GtkWidget *dialog_action_area5;
  GtkWidget *button7;
  GtkWidget *button8;

  filechooserdialog_extract = gtk_file_chooser_dialog_new ("", NULL, GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER, NULL);
  gtk_container_set_border_width (GTK_CONTAINER (filechooserdialog_extract), 5);
  gtk_window_set_type_hint (GTK_WINDOW (filechooserdialog_extract), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox5 = GTK_DIALOG (filechooserdialog_extract)->vbox;
  gtk_widget_show (dialog_vbox5);

  dialog_action_area5 = GTK_DIALOG (filechooserdialog_extract)->action_area;
  gtk_widget_show (dialog_action_area5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area5), GTK_BUTTONBOX_END);

  button7 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button7);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog_extract), button7, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button7, GTK_CAN_DEFAULT);

  button8 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (button8);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog_extract), button8, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button8, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) button7, "clicked",
                            G_CALLBACK (on_button7_clicked),
                            GTK_OBJECT (filechooserdialog_extract));
  g_signal_connect_swapped ((gpointer) button8, "clicked",
                            G_CALLBACK (on_button8_clicked),
                            GTK_OBJECT (filechooserdialog_extract));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog_extract, filechooserdialog_extract, "filechooserdialog_extract");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog_extract, dialog_vbox5, "dialog_vbox5");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog_extract, dialog_action_area5, "dialog_action_area5");
  GLADE_HOOKUP_OBJECT (filechooserdialog_extract, button7, "button7");
  GLADE_HOOKUP_OBJECT (filechooserdialog_extract, button8, "button8");

  gtk_widget_grab_default (button8);
  return filechooserdialog_extract;
}

GtkWidget*
create_change_pass (void)
{
  GtkWidget *change_pass;
  GtkWidget *dialog_vbox6;
  GtkWidget *table1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label3;
  GtkWidget *dialog_action_area6;
  GtkWidget *change_pass_cancelbutton;
  GtkWidget *okbutton2;

  change_pass = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (change_pass), _("Change Password"));
  gtk_window_set_resizable (GTK_WINDOW (change_pass), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (change_pass), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox6 = GTK_DIALOG (change_pass)->vbox;
  gtk_widget_show (dialog_vbox6);
  gtk_widget_set_size_request (dialog_vbox6, 350, 200);

  table1 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox6), table1, TRUE, FALSE, 0);
  gtk_widget_set_size_request (table1, 325, -1);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 15);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_table_attach (GTK_TABLE (table1), entry2, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_visibility (GTK_ENTRY (entry2), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 9679);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_table_attach (GTK_TABLE (table1), entry3, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_visibility (GTK_ENTRY (entry3), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 9679);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_table_attach (GTK_TABLE (table1), entry4, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_visibility (GTK_ENTRY (entry4), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 9679);

  label4 = gtk_label_new (_("New Password"));
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 10, 10);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  label5 = gtk_label_new (_("Confirm Password "));
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 10, 10);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  label3 = gtk_label_new (_("Current Password"));
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table1), label3, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 10, 10);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  dialog_action_area6 = GTK_DIALOG (change_pass)->action_area;
  gtk_widget_show (dialog_action_area6);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area6), GTK_BUTTONBOX_END);

  change_pass_cancelbutton = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (change_pass_cancelbutton);
  gtk_dialog_add_action_widget (GTK_DIALOG (change_pass), change_pass_cancelbutton, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (change_pass_cancelbutton, GTK_CAN_DEFAULT);

  okbutton2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (change_pass), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) change_pass_cancelbutton, "clicked",
                            G_CALLBACK (on_change_pass_cancelbutton_clicked),
                            GTK_OBJECT (change_pass));
  g_signal_connect_swapped ((gpointer) okbutton2, "clicked",
                            G_CALLBACK (on_okbutton2_clicked),
                            GTK_OBJECT (change_pass));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (change_pass, change_pass, "change_pass");
  GLADE_HOOKUP_OBJECT_NO_REF (change_pass, dialog_vbox6, "dialog_vbox6");
  GLADE_HOOKUP_OBJECT (change_pass, table1, "table1");
  GLADE_HOOKUP_OBJECT (change_pass, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (change_pass, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (change_pass, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (change_pass, label4, "label4");
  GLADE_HOOKUP_OBJECT (change_pass, label5, "label5");
  GLADE_HOOKUP_OBJECT (change_pass, label3, "label3");
  GLADE_HOOKUP_OBJECT_NO_REF (change_pass, dialog_action_area6, "dialog_action_area6");
  GLADE_HOOKUP_OBJECT (change_pass, change_pass_cancelbutton, "change_pass_cancelbutton");
  GLADE_HOOKUP_OBJECT (change_pass, okbutton2, "okbutton2");

  return change_pass;
}

GtkWidget*
create_about_dialog (void)
{
  GtkWidget *about_dialog;
  GtkWidget *dialog_vbox7;
  GtkWidget *vbox4;
  GtkWidget *image19;
  GtkWidget *about_label;
  GtkWidget *dialog_action_area7;
  GtkWidget *closebutton1;

  about_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (about_dialog), _("About"));
  gtk_window_set_type_hint (GTK_WINDOW (about_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox7 = GTK_DIALOG (about_dialog)->vbox;
  gtk_widget_show (dialog_vbox7);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox7), vbox4, TRUE, TRUE, 0);

  image19 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (vbox4), image19, TRUE, TRUE, 0);

  about_label = gtk_label_new (_("This is the about window. Here the about of the software shall come"));
  gtk_widget_show (about_label);
  gtk_box_pack_start (GTK_BOX (vbox4), about_label, FALSE, FALSE, 0);
  gtk_widget_set_size_request (about_label, -1, 100);
  gtk_label_set_line_wrap (GTK_LABEL (about_label), TRUE);

  dialog_action_area7 = GTK_DIALOG (about_dialog)->action_area;
  gtk_widget_show (dialog_action_area7);

  closebutton1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (about_dialog), closebutton1, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton1, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (about_dialog, about_dialog, "about_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (about_dialog, dialog_vbox7, "dialog_vbox7");
  GLADE_HOOKUP_OBJECT (about_dialog, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (about_dialog, image19, "image19");
  GLADE_HOOKUP_OBJECT (about_dialog, about_label, "about_label");
  GLADE_HOOKUP_OBJECT_NO_REF (about_dialog, dialog_action_area7, "dialog_action_area7");
  GLADE_HOOKUP_OBJECT (about_dialog, closebutton1, "closebutton1");

  return about_dialog;
}

GtkWidget*
create_add_user (void)
{
  GtkWidget *add_user;
  GtkWidget *dialog_vbox8;
  GtkWidget *vbox5;
  GtkWidget *table3;
  GtkWidget *labell;
  GtkWidget *add_user_name;
  GtkWidget *labellll;
  GtkWidget *labeellllll;
  GtkWidget *add_user_pass;
  GtkWidget *add_user_conf_pass;
  GtkWidget *add_user_label;
  GtkWidget *dialog_action_area8;
  GtkWidget *cancelbutton1;
  GtkWidget *add_user_ok;

  add_user = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (add_user), _("Add New User"));
  gtk_window_set_type_hint (GTK_WINDOW (add_user), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox8 = GTK_DIALOG (add_user)->vbox;
  gtk_widget_show (dialog_vbox8);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (dialog_vbox8), vbox5, TRUE, TRUE, 0);

  table3 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (vbox5), table3, TRUE, FALSE, 5);
  gtk_table_set_row_spacings (GTK_TABLE (table3), 10);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 5);

  labell = gtk_label_new (_("New Username"));
  gtk_widget_show (labell);
  gtk_table_attach (GTK_TABLE (table3), labell, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (labell), 0, 0.5);

  add_user_name = gtk_entry_new ();
  gtk_widget_show (add_user_name);
  gtk_table_attach (GTK_TABLE (table3), add_user_name, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (add_user_name), 9679);

  labellll = gtk_label_new (_("Password"));
  gtk_widget_show (labellll);
  gtk_table_attach (GTK_TABLE (table3), labellll, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (labellll), 0, 0.5);

  labeellllll = gtk_label_new (_("Confirm Password"));
  gtk_widget_show (labeellllll);
  gtk_table_attach (GTK_TABLE (table3), labeellllll, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (labeellllll), 0, 0.5);

  add_user_pass = gtk_entry_new ();
  gtk_widget_show (add_user_pass);
  gtk_table_attach (GTK_TABLE (table3), add_user_pass, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_visibility (GTK_ENTRY (add_user_pass), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (add_user_pass), 9679);

  add_user_conf_pass = gtk_entry_new ();
  gtk_widget_show (add_user_conf_pass);
  gtk_table_attach (GTK_TABLE (table3), add_user_conf_pass, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_visibility (GTK_ENTRY (add_user_conf_pass), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (add_user_conf_pass), 9679);

  add_user_label = gtk_label_new ("");
  gtk_widget_show (add_user_label);
  gtk_box_pack_start (GTK_BOX (vbox5), add_user_label, FALSE, FALSE, 5);

  dialog_action_area8 = GTK_DIALOG (add_user)->action_area;
  gtk_widget_show (dialog_action_area8);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area8), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (add_user), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  add_user_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (add_user_ok);
  gtk_dialog_add_action_widget (GTK_DIALOG (add_user), add_user_ok, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (add_user_ok, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) cancelbutton1, "clicked",
                            G_CALLBACK (on_cancelbutton1_clicked),
                            GTK_OBJECT (add_user));
  g_signal_connect_swapped ((gpointer) add_user_ok, "clicked",
                            G_CALLBACK (on_add_user_ok_clicked),
                            GTK_OBJECT (add_user));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (add_user, add_user, "add_user");
  GLADE_HOOKUP_OBJECT_NO_REF (add_user, dialog_vbox8, "dialog_vbox8");
  GLADE_HOOKUP_OBJECT (add_user, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (add_user, table3, "table3");
  GLADE_HOOKUP_OBJECT (add_user, labell, "labell");
  GLADE_HOOKUP_OBJECT (add_user, add_user_name, "add_user_name");
  GLADE_HOOKUP_OBJECT (add_user, labellll, "labellll");
  GLADE_HOOKUP_OBJECT (add_user, labeellllll, "labeellllll");
  GLADE_HOOKUP_OBJECT (add_user, add_user_pass, "add_user_pass");
  GLADE_HOOKUP_OBJECT (add_user, add_user_conf_pass, "add_user_conf_pass");
  GLADE_HOOKUP_OBJECT (add_user, add_user_label, "add_user_label");
  GLADE_HOOKUP_OBJECT_NO_REF (add_user, dialog_action_area8, "dialog_action_area8");
  GLADE_HOOKUP_OBJECT (add_user, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (add_user, add_user_ok, "add_user_ok");

  return add_user;
}

