/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_pass_dialog (void);
GtkWidget* create_window1 (void);
GtkWidget* create_filechooserdialog_file (void);
GtkWidget* create_filechooserdialog_dir (void);
GtkWidget* create_filechooserdialog_extract (void);
GtkWidget* create_change_pass (void);
GtkWidget* create_about_dialog (void);
GtkWidget* create_add_user (void);
